version: "3.8"
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app/api
      - /home/ubuntu/dev/projects/Docker_Course/app/api/node_modules
  myblog:
    build: ./myblog
    container_name: myblog_c
    ports:
      - '3000:3000'
    volumes:
      - ./myblog:/app/myblog
      - /home/ubuntu/dev/projects/Docker_Course/app/myblog/node_modules
    stdin_open: true